[package]
name = "avrox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

avro-rs = "0.13"
env_logger = "0.11"
sha2 = "0.11.0-pre.3"
